### ISSUE TITLE
Adding get_grid_around_beam_direction

### ISSUE THREAD

**Issue by pc494** [pyxem/diffsims#108]
**Describe the bug**
This functionality (which was in v0.2) relied on now deleted architecture and was set to raise an error in #104, it should be a fairly simple orix wrap and we should probably do it for v0.3

**Comment by dnjohnstone** [comment]
@pc494 I've pushed this to 0.4.0 because I think that's what you were suggesting, is that correct?

**Comment by pc494** [comment]
Sorry, the things all have similar names. I need to fix this for v0.3

**Comment by pc494** [comment]
#115 closed this too
