### ISSUE TITLE
save/load functions need overhaul

### ISSUE THREAD

**Issue by dnjohnstone** [pyxem/diffsims#11]
Saving/loading is currently pretty ugly - only defined for library objects and just done by some pretty basic pickle-ing. Now that diffsims is separate from pyxem it's more obvious that this needs to be addressed properly.

**Comment by pc494** [comment]
Unless somebody has very good solution that will be easy to make work I'm going to push this to `0.3.0`

**Comment by dnjohnstone** [comment]
I think the solution here should be to create an hdf5 save/load interface following a pattern similar to https://github.com/pyxem/orix/pull/67

Does that sound ok to others?

**Comment by hakonanes** [comment]
For this I would recommend using functions similar to `hdf5group2dict()` (https://github.com/pyxem/orix/blob/master/orix/io/plugins/orix_hdf5.py#L59) and `dict2hdf5group()` (https://github.com/pyxem/orix/blob/master/orix/io/plugins/orix_hdf5.py#L334). They have been adapted from HyperSpy's HDF5 plugin (hspy: https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/io_plugins/hspy.py#L405, https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/io_plugins/hspy.py#L590). By passing `recursive=True` to `hdf5group2dict()`, one can read datasets within groups within groups... into nested dictionaries. Likewise, nested dictionaries can be written to datasets within groups within groups... within an opened HDF5 group/file. This makes creating HDF5 IO quite OK.

**Comment by hakonanes** [comment]
Is there any interest in this? I haven't seen any. I suggest to close, but re-open whenever the need arises.

**Comment by pc494** [comment]
agreed, closing.
