### ISSUE TITLE
g_max argument not used in the get_plot method of DiffractionSimulation

### ISSUE THREAD

**Issue by isabelwood100** [pyxem/diffsims#116]
g_max argument not used in the get_plot method of DiffractionSimulation - it should be used or removed.

**Comment by pc494** [comment]
Used is probably the correct answer, will you do it @isabelwood100 or shall I pick it up on my pre-release sweep?

**Comment by dnjohnstone** [comment]
I think it's probably one for the sweep since @isabelwood100 finished her project today.
