### ISSUE TITLE
Readthedocs diffsims API documentation?

### ISSUE THREAD

**Issue by hakonanes** [pyxem/diffsims#126]
kikuchipy now depends on diffsims for electron scattering and diffraction (namely the `crystallography.ReciprocalLatticePoint` class): https://github.com/pyxem/kikuchipy/pull/220. I would therefore want the diffsims API to be easily browsable like kikuchipy's (https://kikuchipy.org/en/latest/reference.html) or orix' (https://orix.readthedocs.io/en/stable/reference.html).

The intersphinx functionality (click e.g. on the `Rotation` link in the "Parameters" docstring here: https://kikuchipy.org/en/latest/reference.html#kikuchipy.generators.EBSDSimulationGenerator) is also very nice, which becomes more important as kikuchipy depends more and more on orix (and hopefully diffsims).

I volunteer to set up a simple Readthedocs documentation available via https://diffsims.rtfd.io, as I did for orix.

**Comment by pc494** [comment]
Yes please @hakonanes, that would be great :)

**Comment by pc494** [comment]
Would this still work if we released it at a patch level? If so could we include it as well as the fix to #125 + whatever I find when making the demos into a `0.3.1`?

**Comment by hakonanes** [comment]
Yes, shouldn't be a problem. Readthedocs only needs a config file and a doc directory to build from.

**Comment by hakonanes** [comment]
Made a v0.3.1 patch milestone to keep track of that release.

**Comment by pc494** [comment]
Great stuff, thank you :)
