### ISSUE TITLE
"Simulation matching" utilities

### ISSUE THREAD

**Issue by pc494** [pyxem/diffsims#134]
image comparisons probably belong here. Can be a single module, with functions, ideally of the form:

```python
def match_function(image_1,image_2,image_1_support=None):
           if image_1_support is None:
                 z = image_1 * image_2 / image_1**(3/2)
           else:
                 z = image_1 * image_2 / image_1_support

           return z

```
The idea is of `_support` is that you can pre-calculate as much as possible in potential mapping cases.

These ideas came from the work in https://github.com/pyxem/pyxem/pull/654, which concluded with the realisation that for this kind of work you would have both lazy experimental data and lazy library data.

**Comment by hakonanes** [comment]
As a note to others, there's an ongoing discussion of a separate matching package here https://github.com/pyxem/pyxem/issues/638.

@onatlandsmyr is working on a `kikuchipy.indexing` module (not itself depending on HyperSpy) with a framework which we at some point should discuss separating into its own package... Do you mean this work (and relevant parts in pyxem) should be part of diffsims instead?

**Comment by pc494** [comment]
Sorry @hakonanes, the work in Kikuchipy seems to be going faster than I had anticipated. I think we will probably want to pull the whole lot out to it's own thing sooner rather than later (ie. potentially before a diffsims release). Maybe an in-person chat is in order.

**Comment by pc494** [comment]
After a discussion (off github) today, it has been decided that this code will not live in diffsims, closing.
