### ISSUE TITLE
Rewriting Libraries (structure and diffraction)

### ISSUE THREAD

**Issue by pc494** [pyxem/diffsims#135]
(again, things from https://github.com/pyxem/pyxem/pull/654)

Both are currently strange, my feeling is that structure would be best as:

```python
{'phase_a':{'structure':@,'orientations':orientation_list}}
```

and diffraction (maybe renamed to `orientation_diffraction`) as

```python
{'phase_a':{(alpha,beta,gamma):{'simulation':@,'intensities':@,'coords':@}}
```

**Comment by hakonanes** [comment]
I guess these are quick thoughts you will elaborate on later... I'm confused why dictionaries are better than classes?

**Comment by pc494** [comment]
you guess correctly, it's the ordering of the nesting. Currently diffraction library is

`{'phase':{'orientations':listoftuples,'simuluations':listofsimulations}}`

which sort of makes sense if you think you can vectorize over them, but given that we can't at the moment I felt like the form described helps to write easier to read code.

**Comment by hakonanes** [comment]
The setup and handling of spot pattern simulations was changed in #205, so I assume this can be closed. Please re-open if I'm wrong.
