### ISSUE TITLE
Rename ReciprocalLatticePoint to ReciprocalLatticeVector?

### ISSUE THREAD

**Issue by hakonanes** [pyxem/diffsims#144]
Should we rename the `ReciprocalLatticePoint` class to `ReciprocalLatticeVector`?

I think yes because "vector" makes you think more of magnitude and direction than just Miller indices. Also, we haven't released kikuchipy v0.3 yet, and v0.2 doesn't depend on diffsims. Thus, this renaming won't break anything now.

**Comment by pc494** [comment]
I think vector is marginally better than point, yes.

**Comment by hakonanes** [comment]
@dnjohnstone, could you give your opinion?

**Comment by dnjohnstone** [comment]
Sorry for the slow reply - yes, I think let's go with ReciprocalLatticeVector - probably better in any case and consistent with the inheritance from orix.vector

**Comment by pc494** [comment]
Is the plan to get ths in for 0.4.0? or the release after?

**Comment by hakonanes** [comment]
its not that important, so it can wait to a 0.5

**Comment by hakonanes** [comment]
I'll make a new PR with a new `ReciprocalLatticeVector` to replace the `ReciprocalLatticePoint` class. We can deprecate the `ReciprocalLatticePoint` class, and remove it in one minor release after the release with `ReciprocalLatticeVector`.
