### ISSUE TITLE
Missing args in get_diffraction_library diffsims 0.3.0

### ISSUE THREAD

**Issue by tiarnan-doherty** [pyxem/diffsims#152]
**Describe the bug**

I'm having an issue running diffsims 0.3.0, any help on where I've gone wrong would be great. I'm trying to generate a diffraction library using the get_diffraction_library command and there seem to be some expected args missing in my installed version when compared to the master on GitHub namely 'max_excitation_error' and 'debye_waller_factors' - see screenshots below. 

**To Reproduce**
Attempt to create a diffraction library from a structure library using args 'max_excitation_error' or 'debye_waller_factors' in diffsims 0.3.0

**Screenshots**
Expected function 
<img width="600" alt="Screenshot 2021-01-07 at 16 01 27" src="https://user-images.githubusercontent.com/40855641/103915124-b269e180-5102-11eb-9993-6104ca16f0d8.png">

Actual function
<img width="942" alt="Screenshot 2021-01-07 at 16 00 49" src="https://user-images.githubusercontent.com/40855641/103915133-b695ff00-5102-11eb-9a1f-3085f8d2e5a9.png">

**Additional context**
I've tried installing diffsims independently of pyxem on mac and windows and get the same issue. I've also verified that version 0.3.0 is installed. All versions installed via anaconda

**Comment by hakonanes** [comment]
Hi @tiarnan-doherty!

I'm not sure I understand you; do you pass those two arguments when calling `get_diffraction_library()`? As you say, they aren't part of diffsims v0.3, but will be part of v0.4 which will be released very soon (next week, I believe).

**Comment by hakonanes** [comment]
To clarify, this is the version of diffsims on GitHub which was released as v0.3: https://github.com/pyxem/diffsims/blob/v0.3.0/diffsims/generators/library_generator.py. Everything commited to the master branch after that hasn't been released yet.

**Comment by pc494** [comment]
Hi @tiarnan-doherty,

Good issue, you're basically correct in everything you say. The version of this function has been changed on `master` and when we release the code (end of the week probably) the syntax you have as "Expected Function" will be the one you need to use.

In the meantime, you've got the 0.3.0 version, which looks (as you say) like "Actual Function", you can check that that is what you would expect by navigating to the "tagged" version on github (see screenshot below).

This (forthcoming change) is to part of a wider move to sort arguments into "detector" and "sample" based ones.

![github_for_td](https://user-images.githubusercontent.com/32455330/103920014-abde6880-5108-11eb-92c5-7f2a4b2cad0b.png)

**Comment by pc494** [comment]
For example, `max_excitation_error` is provided with a  `DiffractionGenerator` in v0.3.0, at some point you would  write something like:

```python
edc = DiffractionGenerator(300,5e-2) # 300 is the electron voltage, 5e-2 is max_excitation_error
```
but we decided that this was slightly unphysical. Discussion of this change can be found in https://github.com/pyxem/diffsims/pull/137

**Comment by tiarnan-doherty** [comment]
Thanks both, that's very helpful! I basically got here because I upgraded from 0.2 recently and was trying to vary the relrod length with DiffractionGenerator and was getting the below
<img width="844" alt="Screenshot 2021-01-07 at 17 26 36" src="https://user-images.githubusercontent.com/40855641/103924174-99b2f900-510d-11eb-9124-6d28b897eb0d.png">

**Comment by pc494** [comment]
Ooops, my mistake (shows how long it's been since I did any research with this code).

In `0.3.0` we've shuffled `max_excitation_error` to the 

`.calculate_ed_data()`

method. This makes it more "sample" and less "microscope". Sorry for the confusion, that's not the best error message I've ever written.

**Comment by tiarnan-doherty** [comment]
Thanks @pc494!
