### ISSUE TITLE
Support Python 3.9

### ISSUE THREAD

**Issue by hakonanes** [pyxem/diffsims#164]
I suggest these changes to the the build matrix:
* Use Python 3.8 and 3.9 (instead of 3.7 and 3.8)
* Add extra step for minimal versions, i.e. Python 3.6 and the minimal package versions stated in setup.py. Whenever this step fails, we can either try to support the older version by changing code, or increment the minimal version.

Including a build step for minimal versions led me to increase minimal supported package versions in [kikuchipy quite substantially](https://github.com/pyxem/kikuchipy/pull/348/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L117).

We should also update setup.py to reflect support for Python 3.8 and 3.9.

I can do all these things when I find the time.

**Comment by pc494** [comment]
I think this is best approach, +1
