### ISSUE TITLE
Tolerance too high for get_library_entries

### ISSUE THREAD

**Issue by pc494** [pyxem/diffsims#173]
**Describe the bug**
The tolerance on the `get_library_entries` of `DiffractionLibrary` is too tight. If everything was staying in degrees `1e-5 ` would be fine but once radians conversions are accounted for something like `1e-2` seems more appropriate.

Thanks to Aaron Chote who brought this to my attention.

The case:

`diff_lib.get_library_entry('phase',angle=np.rad2deg([1.53589,0.29932,-1.53589]))`

will not give (88,17.15,-88)

**Comment by hakonanes** [comment]
What remains here? Is it just to update this line?

https://github.com/pyxem/diffsims/blob/663799422254f1174589020fb8ba4de1796fe7dd/diffsims/libraries/diffraction_library.py#L79

**Comment by pc494** [comment]
Yes, I think so

**Comment by hakonanes** [comment]
OK, I'll do that tomorrow.
