### ISSUE TITLE
Release version 0.5.0

### ISSUE THREAD

**Issue by pc494** [pyxem/diffsims#180]
We're using [the milestone](https://github.com/pyxem/diffsims/milestone/6) to keep track of this release, which is coming in to aid the 0.14.0 release of pyxem.

**Comment by pc494** [comment]
I'm going to tidy this up over the coming days and release.

**Comment by hakonanes** [comment]
I can assist in reviewing where necessary.

**Comment by pc494** [comment]
had a (slight) change of heart, as these changes are not essential for the upcoming workshop (next week) I'm going to leave the actual release until May 9th, will do the cleaning as time arises.

**Comment by din14970** [comment]
Could opt for a minor release. If I'm not mistaken, #172 and #175 are not released but I do use them in the workflows for the orientation mapping paper. Many users might be more comfortable installing a version than a git hash. Any specific reason to hold off?

**Comment by hakonanes** [comment]
I plan to fix #183 now and wrap up #182.

Suggested release schedule:
1. Fix outstanding issues: https://github.com/pyxem/diffsims/milestone/6
2. Release 0.5.0rc1 ~Monday May 30~ Wednesday June 1
3. Release 0.5.0 on ~Wednesday June 1~ Friday June 3 or when upstream packages (pyxem, kikuchipy) are confirmed to work nicely with 0.5.0rc1

I can do the release.

**Comment by pc494** [comment]
Sorry, this was me being slow on the reviews. I think we're now ready for the rc?

**Comment by hakonanes** [comment]
Yes, I think so too. Will release tomorrow!

**Comment by hakonanes** [comment]
Release timeline:
- [x] v0.5.0rc1
    - [x] PyPI
- [ ] v0.5.0, planned for Friday June 3
    - [ ] PyPI
    - [ ] conda-forge

**Comment by hakonanes** [comment]
The upload to [TestPyPI](https://test.pypi.org/project/diffsims/), [PyPI](https://pypi.org/project/diffsims/#history) and [Zenodo](https://zenodo.org/record/6603007#.YpdjlDVBwUE) worked as expected.

**Comment by hakonanes** [comment]
kikuchipy's tests run without errors with diffsims v0.5.0rc1 in both the development ([CI log](https://github.com/hakonanes/kikuchipy/actions/runs/2421948195)) and released ([CI log](https://github.com/hakonanes/kikuchipy/actions/runs/2422065164)) versions. pyxem's tests (using diffsims) run without errors with diffsims v0.5.0rc1 as well, see https://github.com/pyxem/pyxem/pull/848.

Based on this it should be safe to release diffsims v0.5.0 on Friday.

**Comment by pc494** [comment]
This is almost there now, @hakonanes are you happy to tag a version and get everything underway?

**Comment by hakonanes** [comment]
diffsims 0.5.0 is now available from PyPI. Thank you for your review efforts and help, Phillip!

What's left:
- [x] Release on conda-forge

I'll close this issue and the milestone once the above list is done.
