### ISSUE TITLE
Add interactive/visual pattern generation

### ISSUE THREAD

**Issue by dnjohnstone** [pyxem/diffsims#21]
@shogas created a script (https://github.com/shogas/sped_processing_playground/blob/master/pattern_gen_visualizer.py) for manually tweaking kinematical simulation parameters - it would be good to put this in to the diffsims code base

**Comment by pc494** [comment]
Did we drop the `.as_signal()` method?

**Comment by dnjohnstone** [comment]
I think we had to so that diffsims didn't depend on either pyxem or hyperspy. Not sure what we should do about that...

**Comment by pc494** [comment]
> I think we had to so that diffsims didn't depend on either pyxem or hyperspy. Not sure what we should do about that...

That makes perfect sense, I'll write a `numpy + matplotlib` only implementation - I think it's worth having as functionality.

**Comment by pc494** [comment]
A similar functionality for parameter tweaking was added to pyxem  but it relies on hyperspy for the plotting; see - https://github.com/pyxem/pyxem/pull/451/

The `numpy + matplotlib` solution was added by #25

**Comment by pc494** [comment]
Will combine this with my efforts on #7

**Comment by pc494** [comment]
The components of this that haven't been done should probably be in workflow. Until they are needed I'm not going to make a priority of this.
