### ISSUE TITLE
NumPy v2 compatibility

### ISSUE THREAD

**Issue by hakonanes** [pyxem/diffsims#227]
Recent builds show incompatibility with NumPy v2: https://github.com/pyxem/diffsims/actions/runs/11225925305/job/31205494222?pr=226. Needs fixing!

I suggest to fix this and make a v0.6.1 patch release, as the changelog shows no new features on *main*.

**Comment by CSSFrancis** [comment]
@hakonanes Perfect! Want me to make the PR?  I checked with the ruff numpy 2.0.0 check a bit ago but obviously it isn't perfect :)

**Comment by CSSFrancis** [comment]
Fixed in #228

**Comment by hakonanes** [comment]
Yup, the build in #228 for e.g. macOS Python 3.11 shows diffsims to be compatible with NumPy 2.

**Comment by CSSFrancis** [comment]
Closed with v0.6.1 release

**Comment by hakonanes** [comment]
0.6.1 is released on conda-forge as well: https://anaconda.org/conda-forge/diffsims
