### ISSUE TITLE
EMsoft now has kinematical PED simulations and Python wrappers for some modules

### ISSUE THREAD

**Issue by hakonanes** [pyxem/diffsims#27]
I haven't tried any of the functionality mentioned below out yet, but posted this as an fyi. The issue can be closed at your convenience.

The newly released EMsoft version 4.3 can simulate kinematical PED patterns via the `EMPEDkin` routine (https://github.com/EMsoft-org/EMsoft/blob/f5e6c8a5cb186478f5d34597708d4962f245a794/Source/TEM/EMPEDkin.f90).

Also included are Python wrappers for a lot of the modules available via a sub directory in the main repo named pyEMsoft, see these links:
1. https://github.com/EMsoft-org/EMsoft/wiki/python-examples
2. https://github.com/EMsoft-org/EMsoft/wiki/python-wrapper-installation
3. https://github.com/EMsoft-org/EMsoft/blob/develop/Source/pyEMsoft/docs/pyEMsoft.rst

**Comment by dnjohnstone** [comment]
Thanks @hwagit I think we could be interested in this, but only if we can find a way to make at least the necessary parts of EMSoft install using conda.

In the broadest sense, we absolutely want to make diffsims a convenient python interface for high quality diffraction simulations and using EMSoft to do some of that would be great.

**Comment by hakonanes** [comment]
Fair point @dnjohnstone. Although I guess that won't happen in the near future, and I don't know if it is actually possible, I would assume the chance that the core EMsoft developers will consider this will increase if people start to use it.

For further reference:
* landing page: http://vbff.materials.cmu.edu/pyemsoft/
* documentation: https://pyemsoftreadthedocs.readthedocs.io/en/latest/index.html
