### ISSUE TITLE
Rotations conventions seem inconsistent with diffpy's

### ISSUE THREAD

**Issue by pc494** [pyxem/diffsims#28]
**Describe the bug**
We use transform3d for our rotation matrices, which are applied on the **left** [1].
In `simulate_rotated_structure` we pass one such matrix to diffpy, and it is applied on the **right** [2]

This means that the (alpha,beta,gamma) that is eventually returned (from say a template match) is not "correct" but is (I think) consistent, as the error propagates in a "safe" way.

[1] https://matthew-brett.github.io/transforms3d/conventions.html
[2] https://www.diffpy.org/diffpy.structure/mod_lattice.html#diffpy.structure.lattice.Lattice.base

**Comment by dnjohnstone** [comment]
Oh - that's a bad one.... Well noticed.

**Comment by shogas** [comment]
Yes, I had problems with that and think I got it correct most places by passing the transpose/inverse where appropriate, but there are likely some places I missed. The issue should probably be documented (after fixing) anywhere it comes up.

**Comment by EirikOpheim** [comment]
I believe a temporary solution to the problem might lie in reversing the input order of the Euler angles when producing the matrix given to diffpy. This would explain the behaviour seen in Issue 19 in Orix, where (-80,10,0) gives the same output as (10,10,0). I have added to the method "get_diffractin_library" in diffsims generators: 
for i, orientation in enumerate(tqdm(orientations, leave=False)):
        matrix = euler2mat(*np.deg2rad(**orientation[::-1]**), 'rzxz')
Now I get a result that seems consistent with the orix implementation. Producing a misorientation map between the truth value and the template matching result with the truth values as template I obtain the following map (to the right) : 
![ResiultTemplateMatch](https://user-images.githubusercontent.com/34092703/70030827-4c7b6400-15aa-11ea-8715-7075fc3359b1.png)

Appart from the effects of the boundaries, of the minimum symmetry area (white dots) and a few misses of 5 degrees (slight gray dots) the result is perfect.

**Comment by EirikOpheim** [comment]
While testing for a template of 2 degrees resolution the results were no longer so pretty, so my solution might not be working after all.. I will try looking a bit more at the problem, and see if I come up with something!
