### ISSUE TITLE
Minor enhancement for function get_points_in_sphere (sim_util)

### ISSUE THREAD

**Issue by EirikOpheim** [pyxem/diffsims#37]
Minor Enhancement: 
For the function get_points_in_sphere(reciprocal_lattice, reciprocal_radius) in diffsims/sim_util I think we can replace ceil() with floor() and save some evaluations that will not pass the following test of being inside the reciprocal radius anyways. This is as the furthest we can go from the center in discrete steps along the a-axis should be floor(a/reciprocal_radius).

I am not sure how much time this will save, but this function seems to be called a lot, so maybe it can save a few minutes for big projects. If we worry about missing a point due to machine precision round-off error, I guess we could write floor(a/reciprocal_radius + pow(10,-14)).

**Comment by pc494** [comment]
Replacing `ceil` with `floor` here looks safe to me. I doubt the performance enhancement is substantial. I am also not convinced machine-precision will play a role.
