### ISSUE TITLE
Related packages

### ISSUE THREAD

**Issue by dnjohnstone** [pyxem/diffsims#38]
Might be worth considering whether this package (https://github.com/spacetelescope/poppy) is at all relevant to us.

**Comment by dnjohnstone** [comment]
Also this: https://github.com/dkriegner/xrayutilities

**Comment by dnjohnstone** [comment]
Also this: https://onlinelibrary.wiley.com/iucr/doi/10.1107/S1600576719008471

**Comment by hakonanes** [comment]
We now have a list of [related projects](https://diffsims.readthedocs.io/en/latest/related_projects.html) in the documentation where projects mentioned here could be added to.

**Comment by pc494** [comment]
Okay this is closeable on the new release.

**Comment by hakonanes** [comment]
When is the due date for diffsims v0.5?

**Comment by hakonanes** [comment]
@pc494, do you plan to release 0.5 before releasing pyxem 0.14?

**Comment by pc494** [comment]
Excellent question. I think the answer is yes. But I fear the route to achieving that will be 0.14.0.rc.1 is complete. Some people (probably including me) hackathon diffsims up to 0.5.0, check it against 0.14.0 and go from there. Inelegant I'll grant you, but probably more manageable.

I'll have another diffsims sweep and put everything in the 0.5.0 release milestone.

**Comment by pc494** [comment]
Will use #180 for coordination of this release.

**Comment by hakonanes** [comment]
Sounds good.

I have plans to create the ReciprocalLatticeVector class to finally replace ReciprocalLatticePoint (based on orix' Miller class, will give kikuchipy geometrical EBSD simulations of all point groups), but haven't got the time at the moment, so this is something for later.

> I'll have another diffsims sweep and put everything in the 0.5.0 release milestone.

Regarding milestones: how about dropping the "future" one and considering all un-milestoned issues "future"?

**Comment by pc494** [comment]
> Regarding milestones: how about dropping the "future" one and considering all un-milestoned issues "future"?

Yeah, it probably would be better to tag the issues as "speculative" or something similar.

**Comment by hakonanes** [comment]
Agree. Tagging some issues "future" while others aren't tagged gives me the impression that the former issues are more prioritized than the latter ones, which I think hasn't been the case. I removed "future" from issues and closed the milestone.

**Comment by hakonanes** [comment]
The 0.5.0 release will go out soon.
