### ISSUE TITLE
ZAP map generator

### ISSUE THREAD

**Issue by dnjohnstone** [pyxem/diffsims#7]
It is often useful to simulate electron diffraction from various zone axes i.e. to produce a zone axis pattern (ZAP) map. A generator for this application would be useful.

**Comment by shogas** [comment]
Just some additional context: Is this a generator for "list of [uvw] zone axis" -> "list/map/signal of diffraction patterns for corresponding directions"? In that case, `simulate_rotated_structure` https://github.com/pyxem/diffsims/blob/1a4dade6a24e05ea7e58d730d5d79ecbdbd3c9d6/diffsims/utils/sim_utils.py#L346 is a good starting point, along with some code for mapping `[uvw]` to a rotation matrix. I think diffpy.structure already provides this functionality?

**Comment by dnjohnstone** [comment]
Yes, that's right @shogas - as you say it shouldn't be too difficult to implement, it was a suggestion from @M0hsend to provide a convenience function for use during experiments when it's handy to be able to figure out what major zone axis you've found yourself down right now!

**Comment by pc494** [comment]
#62 closed this.
