### ISSUE TITLE
Kinematical CBED simulation & disc overlap calculation

### ISSUE THREAD

**Issue by dnjohnstone** [pyxem/diffsims#81]
It would be good to add a simple kinematical simulation of a CBED disk pattern and allow simple calculation of overlap between discs.

This should be fairly easy to do by taking the output of the basic simulator and applying a convolution with a top hat function.

The following code snippet from @chrisallen80 would give a way to calculate the percentage overlap of neighbouring discs, which we could initialize with the disc centers from our current kinematical simulator perhaps.

```
import numpy as np
r = 4e-10 #probe radius
d = 0.73e-10 # probe spacing
x_pos  = 0.5 * d # x coordinate of circle intersection
y_pos = np.sqrt(r**2 - x_pos**2) # y coordinate of circle intersection
theta = 2*np.arctan(y_pos / x_pos) # angle subtended by overlap
A_overlap =  (r**2 * theta) - (2*x_pos*y_pos) # area of overlap
A_probe = np.pi * r**2
Percentage_overlap =100 *  A_overlap / A_probe
print('x, y : ', x_pos, y_pos)
print('theta : ', theta )
print('overlap area : ', A_overlap)
print('probe area : ', A_probe)
print('overlap  % : ', Percentage_overlap)
```

**Comment by pc494** [comment]
Deemed out of scope at present.
