### ISSUE TITLE
Typo in ATOMIC_SCATTERING_PARAMS_PENG

### ISSUE THREAD

**Issue by M0hsend** [pyxem/diffsims#91]
**Describe the bug**
In [here](https://github.com/pyxem/diffsims/blob/11c75ba262525d080e6a64c90812ce17077559b6/diffsims/utils/atomic_diffraction_generator_support/discretise_utils.py#L1030) 

there is a typo: Al is typed as A1. Passing a structure with Al in it results in `ValueError: Atom Z='Al' is not supported`

**Comment by dnjohnstone** [comment]
Thanks - do you want to fix in a PR or do you want one of us to do it?

**Comment by M0hsend** [comment]
Happy to submit a quick fix. 
I also had another issue with loading a cif file (Anorthite- attached)
[anorthite_cryst.txt](https://github.com/pyxem/diffsims/files/4695718/anorthite_cryst.txt)
where I get `ValueError: Atom Z='Oa' is not supported`, not reading the Oxygen sites correctly. This is a `diffpy.structure.parser`  issue. Not sure what is the best way to fix that?
